/**
 */
package action_assurancecase.provider;

import action_assurancecase.util.Action_assurancecaseAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Action_assurancecaseItemProviderAdapterFactory extends Action_assurancecaseAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Action_assurancecaseItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link action_assurancecase.AssuranceCaseActionPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssuranceCaseActionPackageItemProvider assuranceCaseActionPackageItemProvider;

	/**
	 * This creates an adapter for a {@link action_assurancecase.AssuranceCaseActionPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssuranceCaseActionPackageAdapter() {
		if (assuranceCaseActionPackageItemProvider == null) {
			assuranceCaseActionPackageItemProvider = new AssuranceCaseActionPackageItemProvider(this);
		}

		return assuranceCaseActionPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link action_assurancecase.CreateAssuranceCasePackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateAssuranceCasePackageItemProvider createAssuranceCasePackageItemProvider;

	/**
	 * This creates an adapter for a {@link action_assurancecase.CreateAssuranceCasePackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateAssuranceCasePackageAdapter() {
		if (createAssuranceCasePackageItemProvider == null) {
			createAssuranceCasePackageItemProvider = new CreateAssuranceCasePackageItemProvider(this);
		}

		return createAssuranceCasePackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link action_assurancecase.CreateAssuranceCasePackageInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateAssuranceCasePackageInterfaceItemProvider createAssuranceCasePackageInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link action_assurancecase.CreateAssuranceCasePackageInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateAssuranceCasePackageInterfaceAdapter() {
		if (createAssuranceCasePackageInterfaceItemProvider == null) {
			createAssuranceCasePackageInterfaceItemProvider = new CreateAssuranceCasePackageInterfaceItemProvider(this);
		}

		return createAssuranceCasePackageInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link action_assurancecase.CreateAssuranceCasePackageBinding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateAssuranceCasePackageBindingItemProvider createAssuranceCasePackageBindingItemProvider;

	/**
	 * This creates an adapter for a {@link action_assurancecase.CreateAssuranceCasePackageBinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateAssuranceCasePackageBindingAdapter() {
		if (createAssuranceCasePackageBindingItemProvider == null) {
			createAssuranceCasePackageBindingItemProvider = new CreateAssuranceCasePackageBindingItemProvider(this);
		}

		return createAssuranceCasePackageBindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link action_assurancecase.UpdateAssuranceCaseElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UpdateAssuranceCaseElementItemProvider updateAssuranceCaseElementItemProvider;

	/**
	 * This creates an adapter for a {@link action_assurancecase.UpdateAssuranceCaseElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUpdateAssuranceCaseElementAdapter() {
		if (updateAssuranceCaseElementItemProvider == null) {
			updateAssuranceCaseElementItemProvider = new UpdateAssuranceCaseElementItemProvider(this);
		}

		return updateAssuranceCaseElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link action_assurancecase.DeleteAssuranceCaseElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeleteAssuranceCaseElementItemProvider deleteAssuranceCaseElementItemProvider;

	/**
	 * This creates an adapter for a {@link action_assurancecase.DeleteAssuranceCaseElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeleteAssuranceCaseElementAdapter() {
		if (deleteAssuranceCaseElementItemProvider == null) {
			deleteAssuranceCaseElementItemProvider = new DeleteAssuranceCaseElementItemProvider(this);
		}

		return deleteAssuranceCaseElementItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (assuranceCaseActionPackageItemProvider != null) assuranceCaseActionPackageItemProvider.dispose();
		if (createAssuranceCasePackageItemProvider != null) createAssuranceCasePackageItemProvider.dispose();
		if (createAssuranceCasePackageInterfaceItemProvider != null) createAssuranceCasePackageInterfaceItemProvider.dispose();
		if (createAssuranceCasePackageBindingItemProvider != null) createAssuranceCasePackageBindingItemProvider.dispose();
		if (updateAssuranceCaseElementItemProvider != null) updateAssuranceCaseElementItemProvider.dispose();
		if (deleteAssuranceCaseElementItemProvider != null) deleteAssuranceCaseElementItemProvider.dispose();
	}

}
