<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="conceptual_mapping" nsURI="http://cacm.conceptual.mapping/1.0"
    nsPrefix="conceptual_mapping_">
  <eClassifiers xsi:type="ecore:EClass" name="MapModel" eSuperTypes="general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapGroup" upperBound="-1"
        eType="#//MapGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="map" upperBound="-1" eType="#//Map"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapGroup" eSuperTypes="general.ecore#//DescribableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Map" abstract="true" eSuperTypes="general.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MapKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapGroup" eType="#//MapGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapJustification" eType="#//MapJustification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalenceMap" eSuperTypes="#//Map">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="ecore:EClass general.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="ecore:EClass general.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplianceMap" eSuperTypes="#//Map">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="ecore:EClass general.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapJustification" eSuperTypes="general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explanation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MapKind">
    <eLiterals name="full"/>
    <eLiterals name="partial" value="1"/>
    <eLiterals name="noMap" value="2"/>
  </eClassifiers>
</ecore:EPackage>
