<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="executed_process" nsURI="http://cacm.executed.process/1.0" nsPrefix="executed_process_">
  <eClassifiers xsi:type="ecore:EClass" name="ExecutedProcessModel" eSuperTypes="general.ecore#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" upperBound="-1"
        eType="#//ExecutedProcessAsset" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutedProcessAsset" abstract="true"
      eSuperTypes="general.ecore#//DescribableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutedActivity" eSuperTypes="#//ExecutedProcessAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="ecore:EClass managedArtifact.ecore#//ManagedArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="ecore:EClass managedArtifact.ecore#//ManagedArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subActivity" upperBound="-1"
        eType="#//ExecutedActivity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" upperBound="-1"
        eType="#//ExecutedActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" upperBound="-1"
        eType="#//ExecutedActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsedTechnique" eSuperTypes="#//ExecutedProcessAsset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedArtifact" upperBound="-1"
        eType="ecore:EClass managedArtifact.ecore#//ManagedArtifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant" eSuperTypes="#//ExecutedProcessAsset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" upperBound="-1" eType="#//ParticipantRole"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParticipantRole" eSuperTypes="#//ExecutedProcessAsset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executedActivity" eType="#//ExecutedActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedArtifactEvaluation"
        eType="ecore:EClass managedArtifact.ecore#//ManagedArtifactEvaluation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedArtifact" eType="ecore:EClass managedArtifact.ecore#//ManagedArtifact"/>
  </eClassifiers>
</ecore:EPackage>
