<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uma_method" nsURI="http://unified.method.architecture/method/1.0"
    nsPrefix="uma_method_">
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageableElement" abstract="true"
      eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="MethodElement" abstract="true" eSuperTypes="#//PackageableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="presentationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="briefDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suppressed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderingGuide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodPackage" abstract="true" eSuperTypes="#//MethodElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="global" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childPackages" upperBound="-1"
        eType="#//MethodPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reusedPackages" upperBound="-1"
        eType="#//MethodPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodUnit" abstract="true" eSuperTypes="#//MethodElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authors" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescribableElement" abstract="true"
      eSuperTypes="#//MethodElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shapeIcon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeIcon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentation" eType="#//ContentDescription"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VaraibilityElement" abstract="true"
      eSuperTypes="#//MethodElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variabilityType" eType="#//VariabilityType"
        defaultValueLiteral="na"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variabilityBasedOnElement"
        eType="#//VaraibilityElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentDescription" eSuperTypes="#//MethodUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyConsiderations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longPresentationName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentElement" abstract="true" eSuperTypes="#//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variabilityType" eType="#//VariabilityType"
        defaultValueLiteral="na"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variabilityBasedOnElement"
        eType="#//VaraibilityElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentPackage" eSuperTypes="#//MethodPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentElements" upperBound="-1"
        eType="#//ContentElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guidelines" upperBound="-1"
        eType="#//Guideline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checklists" upperBound="-1"
        eType="#//Checklist"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="termdefinition" upperBound="-1"
        eType="#//TermDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkProduct" eSuperTypes="#//ContentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolMentors" upperBound="-1"
        eType="#//ToolMentor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//WorkProduct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedArtifact" upperBound="-1"
        eType="#//Artifact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Outcome" eSuperTypes="#//WorkProduct"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deliverable" eSuperTypes="#//WorkProduct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliveredWorkProducts"
        upperBound="-1" eType="#//WorkProduct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//ContentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//WorkProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandantoryInput" upperBound="-1"
        eType="#//WorkProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionalInput" upperBound="-1"
        eType="#//WorkProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performedBy" upperBound="-1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionallyPerformedBy"
        upperBound="-1" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolMentors" upperBound="-1"
        eType="#//ToolMentor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//ContentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifies" upperBound="-1"
        eType="#//WorkProduct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guidance" abstract="true" eSuperTypes="#//ContentElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Guideline" eSuperTypes="#//Guidance"/>
  <eClassifiers xsi:type="ecore:EClass" name="Checklist" eSuperTypes="#//Guidance"/>
  <eClassifiers xsi:type="ecore:EClass" name="ToolMentor" eSuperTypes="#//Guidance"/>
  <eClassifiers xsi:type="ecore:EClass" name="Practice" eSuperTypes="#//Guidance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPractices" upperBound="-1"
        eType="#//Practice" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentReferences" upperBound="-1"
        eType="#//ContentElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermDefinition" eSuperTypes="#//Guidance"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentCategory" abstract="true" eSuperTypes="#//ContentElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="WorkProductType" eSuperTypes="#//ContentCategory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workProducts" upperBound="-1"
        eType="#//WorkProduct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="#//ContentCategory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workProducts" upperBound="-1"
        eType="#//WorkProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subDomains" upperBound="-1"
        eType="#//Domain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool" eSuperTypes="#//ContentCategory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolMentors" upperBound="-1"
        eType="#//ToolMentor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisciplineGrouping" eSuperTypes="#//ContentCategory"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleSetGrouping" eSuperTypes="#//ContentCategory"/>
  <eClassifiers xsi:type="ecore:EEnum" name="VariabilityType">
    <eLiterals name="na"/>
    <eLiterals name="contributes" value="1"/>
    <eLiterals name="extends" value="2"/>
    <eLiterals name="replaces" value="3"/>
    <eLiterals name="localContribution" value="4"/>
    <eLiterals name="localReplacement" value="5"/>
    <eLiterals name="extendsReplaecs" value="6"/>
  </eClassifiers>
</ecore:EPackage>
