<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="action_terminology" nsURI="http://org.eclipse.acme.action/1.0/terminology"
    nsPrefix="action_terminology_">
  <eClassifiers xsi:type="ecore:EClass" name="TerminologyActionPackage" eSuperTypes="action_base.ecore#//ActionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="ecore:EClass action_base.ecore#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminologyActionPackages"
        upperBound="-1" eType="#//TerminologyActionPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateTerminologyPackage" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateTerminologyPackageInterface" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateTerminologyPackageBinding" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateTerminologyPackageGroup" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateArtifactElement" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentationElement" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ArtifactElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteArtifactElement" eSuperTypes="action_base.ecore#//Delete">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentationElement" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ArtifactElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateTerminologyAsset" abstract="true"
      eSuperTypes="action_base.ecore#//Create"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateCategory" eSuperTypes="#//CreateTerminologyAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateExpressionElement" abstract="true"
      eSuperTypes="action_base.ecore#//Create">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateExpression" eSuperTypes="#//CreateTerminologyAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateTerm" eSuperTypes="#//CreateTerminologyAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateExpressionElementCategory" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/terminology.ecore#//Category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateExpressionElementValue" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateExpressionElementExpression" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/terminology.ecore#//ExpressionElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="updateTermExternalReference" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateTermOrigin" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ModelElement"/>
  </eClassifiers>
</ecore:EPackage>
