<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="action_artifact" nsURI="http://org.eclipse.acme.action/1.0/artifact"
    nsPrefix="action_artifact_">
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactActionPackage" eSuperTypes="action_base.ecore#//ActionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="ecore:EClass action_base.ecore#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifactActionPackages"
        upperBound="-1" eType="#//ArtifactActionPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArtifactPackage" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArtifactPackageInterface" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArtifactPackageBinding" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArtifactPackageGroup" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateArtifactElement" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentationElement" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ArtifactElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteArtifactElement" eSuperTypes="action_base.ecore#//Delete">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentationElement" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ArtifactElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArtifactAsset" abstract="true"
      eSuperTypes="action_base.ecore#//Create"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArtifact" eSuperTypes="#//CreateArtifactAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateActivity" eSuperTypes="#//CreateArtifactAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateEvent" eSuperTypes="#//CreateArtifactAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateParticipant" eSuperTypes="#//CreateArtifactAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateTechnique" eSuperTypes="#//CreateArtifactAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateResource" eSuperTypes="#//CreateArtifactAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateProperty" eSuperTypes="#//CreateArtifactAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArtifactAssetRelationship" eSuperTypes="#//CreateArtifactAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdatePropertyPurpose" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purpose" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateArtifactAssetRelationshipSource"
      eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateArtifactAssetRelationshipTarget"
      eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateArtifactVersion" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateArtifactDate" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateActivityStartTime" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateActivityEndTime" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateResourceOccurence" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
</ecore:EPackage>
