<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="action_argumentation" nsURI="http://org.eclipse.acme.action/1.0/argumentation"
    nsPrefix="action_argumentation_">
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentationActionPackage" eSuperTypes="action_base.ecore#//ActionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="ecore:EClass action_base.ecore#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentationActionPackages"
        upperBound="-1" eType="#//ArgumentationActionPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArgumentPackage" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArgumentPackageInterface" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArgumentPackageBinding" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArgumentPackageGroup" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateArgumentationElement" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentationElement" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/argumentation.ecore#//ArgumentationElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteArgumentationElement" eSuperTypes="action_base.ecore#//Delete">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentationElement" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/argumentation.ecore#//ArgumentationElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArgumentAsset" abstract="true"
      eSuperTypes="action_base.ecore#//Create"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArtifactReference" eSuperTypes="#//CreateArgumentAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferToArtifact" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredArtifact" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAssertion" abstract="true" eSuperTypes="#//CreateArgumentAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateAssertionDeclaration" abstract="true"
      eSuperTypes="action_base.ecore#//Update"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclareAsserted" eSuperTypes="#//UpdateAssertionDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclareNeedsSupport" eSuperTypes="#//UpdateAssertionDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclareAssumed" eSuperTypes="#//UpdateAssertionDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclareAxiomatic" eSuperTypes="#//UpdateAssertionDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclareDefeated" eSuperTypes="#//UpdateAssertionDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclareAsCited" eSuperTypes="#//UpdateAssertionDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="MakeClaim" eSuperTypes="#//CreateAssertion"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateArgumentReasoning" eSuperTypes="#//CreateArgumentAsset"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAssertedRelationship" abstract="true"
      eSuperTypes="#//CreateAssertion"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAssertedContext" eSuperTypes="#//CreateAssertedRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAssertedEvidence" eSuperTypes="#//CreateAssertedRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAssertedInference" eSuperTypes="#//CreateAssertedRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAssertedArtifactContext" eSuperTypes="#//CreateAssertedRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAssertedArtifactSupport" eSuperTypes="#//CreateAssertedRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateReasoning" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reasoning" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/argumentation.ecore#//ArgumentReasoning"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateMetaClaim" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaClaim" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/argumentation.ecore#//Claim"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateAssertedRelationshipSource" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateAssertedRelationshipTarget" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateIsCounterAssertedRelationship"
      eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCounter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
