<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="action_assurancecase" nsURI="http://org.eclipse.acme.action/1.0/assurancecase"
    nsPrefix="action_assurance_">
  <eClassifiers xsi:type="ecore:EClass" name="AssuranceCaseActionPackage" eSuperTypes="action_base.ecore#//ActionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="ecore:EClass action_base.ecore#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assuranceCaseActionPackages"
        upperBound="-1" eType="#//AssuranceCaseActionPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentationActionPackages"
        upperBound="-1" eType="ecore:EClass action_argumentation.ecore#//ArgumentationActionPackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminologyActionPackages"
        upperBound="-1" eType="ecore:EClass action_terminology.ecore#//TerminologyActionPackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifactActionPackages"
        upperBound="-1" eType="ecore:EClass action_artifact.ecore#//ArtifactActionPackage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAssuranceCasePackage" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAssuranceCasePackageInterface"
      eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateAssuranceCasePackageBinding" eSuperTypes="action_base.ecore#//CreateArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateAssuranceCaseElement" eSuperTypes="action_base.ecore#//Update">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentationElement" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ArtifactElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteAssuranceCaseElement" eSuperTypes="action_base.ecore#//Delete">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentationElement" eType="ecore:EClass ../../org.eclipse.acme.sacm/model/base.ecore#//ArtifactElement"/>
  </eClassifiers>
</ecore:EPackage>
